[project]
name = "task2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.26",
    "langchain-ollama>=0.3.6",
    "pypdf2>=3.0.1",
    "streamlit>=1.47.0",
]
